<?php
class ManagerCrontab extends Manager{
	function getRow($c_arr){
		if(!is_empty($c_arr["id"])){
			$c_res=$this->database->getItem("crontab",array("id"=>$c_arr["id"]));
		}
		else if(!is_empty($c_arr["code"])){
			$c_res=$this->database->getItem("crontab",array("code"=>$c_arr["code"]));
		}
		//
		if(is_empty($c_res["id"])){
			throw new Exception("AJAX_ERROR_CRONTAB_NOT_FOUND");
		}
		//
		return $c_res["row"];
	}
	//
	function getRowIfEnabled($c_arr){
		$c_row=$this->getRow($c_arr);
		//
		if(((int)$c_row["enabled"])==1){
			return $c_row;
		}
		else{
			throw new Exception("AJAX_ERROR_CRONTAB_NOT_ENABLED");
		}
	}
	//
	function getOrCreateRow($c_arr){
		if(!is_empty($c_arr["id"])){
			$c_res=$this->database->getItem("crontab",array("id"=>$c_arr["id"]));
		}
		else if(!is_empty($c_arr["code"])){
			$c_res=$this->database->getItem("crontab",array("code"=>$c_arr["code"]));
		}
		//
		if(is_empty($c_res["id"]) && !is_empty($c_arr["code"])){
			$c_inup_arr=array(
				"code"=>$c_arr["code"],
				"value"=>"AUTO",
				"tag"=>"AUTO",
				"priority"=>"999999999",
				"date_last_execution"=>"2000-01-01 00:00:00",
				"is_auto"=>"1",
				"enabled"=>"0",
			);
			$c_res=$this->database->inup("crontab",$c_inup_arr,array("code"));
		}
		//
		if(is_empty($c_res["id"])){
			throw new Exception("AJAX_ERROR_CRONTAB_NOT_FOUND");
		}
		//
		return $c_res["row"];
	}
	//
	function updateLastExecution($c_row,$date_last_execution,$bypass=false){
		if(!$bypass)$c_row=$this->getRow($c_row);
		//
		$c_arr=array(
			"id"=>$c_row["id"],
			"date_last_execution"=>$date_last_execution,
		);
		$c_res=$this->database->inup("crontab",$c_arr,array("id"));
	}
	//
	function setCronDFile($swname){
		$text="#".$swname." cron is into /etc/cron.d/".$swname.PHP_EOL.PHP_EOL;
		//
		$crontab_str=shell_exec("crontab -l");
		//
		if(PHP4NS::strpos($crontab_str,$text)===false || PHP4NS::trim($crontab_str)=="no crontab for root"){
			file_put_contents("/tmp/crontab.txt",$crontab_str.$text);
			echo exec("crontab /tmp/crontab.txt");
			//
			echo exec("rm /tmp/crontab.txt");
		}
		//
		$c_sql=sprintf("	SELECT
					c.*
					
					FROM
					crontab AS c
					
					ORDER BY
					priority ASC");
		$c_res=$this->database->getRows($c_sql);
		//
		if($c_res["count"]>0){
			$current_tag="";
			$crontab_txt=sprintf("#Automatically generated by:".DOCUMENT_ROOT."/%s/backend/sync/shark/set_crontab_launcher.sh",$swname);
			//
			foreach($c_res["rows"] as $c_row){
				$c_row=PHP4NS::str_replace("[[PROJECT]]",$swname,$c_row);
				$c_row=PHP4NS::str_replace("[[DOCUMENT_ROOT]]",DOCUMENT_ROOT,$c_row);
				//
				if($c_row["tag"]!=$current_tag){
					$current_tag=$c_row["tag"];
					$crontab_txt.=PHP_EOL.PHP_EOL."###################################################".PHP_EOL."# ".$current_tag.PHP_EOL."###################################################".PHP_EOL;
				}
				//
				if(((int)$c_row["enabled"])==1){
					$crontab_txt.=$c_row["value"].PHP_EOL;
				}
				else{
					$crontab_txt.="#".$c_row["value"].PHP_EOL;
				}
			}
			//
			file_put_contents("/etc/cron.d/".$swname,$crontab_txt);
		}
	}
	//
	//#######################################################################################################################################################################
	// CRONTAB_LOG MANAGER ######################################################################################################################################################
	//#######################################################################################################################################################################
	//
	function inupCrontabLog($c_row,$code,$notes,$bypass=false){
		if(!$bypass)$c_row=$this->getRow($c_row);
		//
		$cl_arr=array(
			"id_crontab"=>$c_row["id"],
			"code"=>$code,
			"notes"=>$notes,
			"ts"=>"now()",
		);
		$cl_res=$this->database->inup("crontab_log",$cl_arr,array("id_crontab","code"));
	}
	//
	function deleteCrontabLog($c_row,$code,$bypass=false){
		if(!$bypass)$c_row=$this->getRow($c_row);
		//
		$cl_delete=sprintf("DELETE FROM crontab_log WHERE id_crontab=%s AND code='%s'",$c_row["id"],$code);
		$this->database->delete($cl_delete);
	}
	//
	function echoLog($tag,$text){
		Log::write(Log::INFO,$tag,$text);
		//
		echo sprintf("%s - %s\n",date("Y-m-d H:i:s"),$text);
	}
	//
	function exec($c_code,$param_arr=array()){
		$c_row=$this->getOrCreateRow(array("code"=>$c_code));
		//
		$param_arr=array_merge($param_arr,array(
			"getDataArr_function"=>$param_arr["getDataArr_function"]??null,
			"getDataKey_function"=>$param_arr["getDataKey_function"]??null,
			"syncData_function"=>$param_arr["syncData_function"]??null,
			//
			"import_error"=>$param_arr["import_error"]??false,
		));
		//
		if(is_empty($param_arr["getDataArr_function"]) || is_empty($param_arr["getDataKey_function"]) || is_empty($param_arr["syncData_function"])){
			throw new Exception("AJAX_ERROR_PARAMETER_NOT_FOUND");
		}
		//
		echo"\n\n-------------------------------------------------------------\n\n";
		echo sprintf("LAUNCH %s",$c_code);
		echo"\n\n";
		//
		$date_current_execution=date("Y-m-d H:i:s");
		//
		//############################################################################################################################################
		//NUOVI
		//############################################################################################################################################
		//
		$this->echoLog($c_code,sprintf("IMPORTAZIONE \"NUOVI\" - INIZIO"));
		//
		$data_arr=$param_arr["getDataArr_function"](array(
			"date_last_execution"=>$c_row["date_last_execution"],
			"data_key"=>null,
		));
		//
		$this->echoLog($c_code,sprintf("RIGHE TROVATE: %s\n",count($data_arr)));
		//
		$data_key_error_arr=array();
		//
		if(!is_empty($data_arr)){
			foreach($data_arr as $data){
				$data_key=$param_arr["getDataKey_function"](array(
					"data"=>$data,
				));
				//
				if(is_empty($data_key)){
					throw new Exception("AJAX_ERROR_DATA_KEY_NOT_FOUND");
				}
				//
				$this->echoLog($c_code,sprintf("[KEY = %s] IMPORTAZIONE",$data_key));
				//
				try{
					$this->database->initTransaction();
					//
					$param_arr["syncData_function"](array(
						"data"=>$data,
					));
					//
					$this->deleteCrontabLog($c_row,$data_key);
					//
					$this->database->commitTransaction();
					//
					$this->echoLog($c_code,sprintf("[KEY = %s] COMPLETATO\n",$data_key));
				}
				catch(Exception $e){
					$this->database->rollbackTransaction();
					//
					$data_key_error_arr[]=$data_key;
					$this->inupCrontabLog($c_row,$data_key,$e->getMessage());
					//
					$this->echoLog($c_code,sprintf("[KEY = %s] ERRORE: %s\n",$data_key,$e->getMessage()));
				}
			}
		}
		//
		$this->echoLog($c_code,sprintf("IMPORTAZIONE \"NUOVI\" - FINE (SUCCESSO: %s, ERRORI: %s)\n",count($data_arr)-count($data_key_error_arr),count($data_key_error_arr)));
		$this->echoLog($c_code,sprintf("########################################################\n"));
		//
		//############################################################################################################################################
		//ERRORI
		//############################################################################################################################################
		//
		if($param_arr["import_error"]){
			$this->echoLog($c_code,sprintf("IMPORTAZIONE \"ERRORI\" - INIZIO"));
			//
			$cl_sql=sprintf("	SELECT DISTINCT
						cl.*
						
						FROM
						crontab_log AS cl
						
						WHERE
						cl.id_crontab=%s
						",
						$c_row["id"]
						);
			$cl_res=$this->database->getRows($cl_sql);
			//
			$this->echoLog($c_code,sprintf("RIGHE TROVATE: %s\n",$cl_res["count"]));
			//
			if($cl_res["count"]>0){
				foreach($cl_res["rows"] as $cl_row){
					$data_key=$cl_row["code"];
					//
					$this->echoLog($c_code,sprintf("[KEY = %s] IMPORTAZIONE",$data_key));
					//
					if(in_array($data_key,$data_key_error_arr)){
						$this->echoLog($c_code,sprintf("[KEY = %s] IN ERRORE FRA I NUOVI\n",$data_key));
						//
						continue;
					}
					//
					$data_arr=$param_arr["getDataArr_function"](array(
						"date_last_execution"=>null,
						"data_key"=>$data_key,
					));
					//
					if(is_empty($data_arr)){
						$this->echoLog($c_code,sprintf("[KEY = %s] DATI NON TROVATI\n",$data_key));
						//
						continue;
					}
					//
					$data=$data_arr[0];
					//
					try{
						$this->database->initTransaction();
						//
						$param_arr["syncData_function"](array(
							"data"=>$data,
						));
						//
						$this->deleteCrontabLog($c_row,$data_key);
						//
						$this->database->commitTransaction();
						//
						$this->echoLog($c_code,sprintf("[KEY = %s] COMPLETATO\n",$data_key));
					}
					catch(Exception $e){
						$this->database->rollbackTransaction();
						//
						$this->echoLog($c_code,sprintf("[KEY = %s] ERRORE: %s\n",$data_key,$e->getMessage()));
					}
				}
			}
			//
			$this->echoLog($c_code,sprintf("IMPORTAZIONE \"ERRORI\" - FINE\n"));
		}
		//
		$this->updateLastExecution($c_row,$date_current_execution);
		//
		echo "\n\n\n\n\n\n\n";
		echo"FINITO";
		echo "\n\n\n\n\n\n\n";

	}
}
?>
