<?php
//
//###################################################################
//### DO NOT EDIT THIS FILE BUT USE config_custom.inc.php INSTEAD ###
//###################################################################
//
define("DOCUMENT_ROOT",dirname(__DIR__,3));
define("SWNAME",basename(dirname(__DIR__,2)));
define("SWPATH",DOCUMENT_ROOT."/".SWNAME."/");
define("SWSIDE",basename(dirname(__DIR__)));
define("SWTYPE",basename(__DIR__));
define("PATH",SWPATH.SWSIDE."/".SWTYPE."/");
define("SHARK","shark_2");
define("CRASH","crash_service_2");
//
require_once(DOCUMENT_ROOT."/".SHARK."/".SWSIDE."/".SWTYPE."/config_shark.inc.php");
require_once(DOCUMENT_ROOT."/".CRASH."/".SWSIDE."/".SWTYPE."/config_crash.inc.php");
?>
